name: Containers CI

on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - ".devcontainer/Containerfile"
  pull_request:
    branches: [main]
    paths:
      - "**.py"
      - ".devcontainer/Containerfile"
  release:
    types: [created]

jobs:
  build_cache_buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v4
        with:
          context: ./
          file: .devcontainer/Containerfile
          push: false
